services:
  ws:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/root/BernsteinFlow
    user: "${UID}:${GID}"
    command: tail -f /dev/null  # Temporary command to keep the container running
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
