services:
  ws:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/root/BernsteinFlow
    user: "${UID}:${GID}"
    command: tail -f /dev/null  # Temporary command to keep the container running
    deploy:
        resources:
            reservations:
                devices:
                  - capabilities: [gpu]
